[package]
name = "example"
version = "0.1.0"
authors = ["Zeb Piasecki <zeb@zebulon.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.50"
serde_json = "1.0.64"
wasm-bindgen = "0.2.73"
wasm-bindgen-futures = "0.4.23"
worker-kv = { path = "../" }
